version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db1
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      